# Edge Detection Toolkit Configuration
# Alle Werte können hier zentral angepasst werden

# System Settings
system:
  # GPU/CUDA Einstellungen
  use_gpu: auto  # auto, true, false
  gpu_memory_fraction: 0.8  # Maximal 80% des GPU-Speichers nutzen (wichtig bei 4GB)
  
  # Multiprocessing
  max_workers: 4  # Anzahl paralleler Prozesse (0 = auto-detect)
  chunk_size: 10  # Bilder pro Batch
  
  # Memory Management (für 16GB RAM System)
  max_image_size: [4096, 4096]  # Maximale Bildgröße vor Resize
  memory_limit_mb: 8192  # Max 8GB für Bildverarbeitung
  
# Download Settings
downloads:
  timeout: 120  # Sekunden
  max_retries: 3
  retry_delay: 5  # Sekunden zwischen Versuchen
  verify_checksums: true
  chunk_size: 8192  # Download chunk size in bytes
  
# Model URLs und Checksums
models:
  hed:
    proto_urls:
      - url: "https://raw.githubusercontent.com/opencv/opencv_extra/master/testdata/dnn/hed_edge_detection/deploy.prototxt"
        checksum: "d41d8cd98f00b204e9800998ecf8427e"  # Beispiel - muss aktualisiert werden
      - url: "https://github.com/s9xie/hed/raw/master/examples/hed/deploy.prototxt"
        checksum: ""
    weights_urls:
      - url: "https://github.com/s9xie/hed/raw/master/examples/hed/hed_pretrained_bsds.caffemodel"
        checksum: ""
      - url: "https://www.dropbox.com/s/example/hed_pretrained_bsds.caffemodel?dl=1"
        checksum: ""
        
  structured_forests:
    model_url: "https://github.com/opencv/opencv_extra/raw/master/testdata/cv/ximgproc/model.yml.gz"
    checksum: ""

  bdcn:
    repo_path: "bdcn_repo"
    model_path: "bdcn_repo/pretrained/bdcn_pretrained.pth"
    weights_url: "https://github.com/zijundeng/BDCN/releases/download/v1.0.0/bdcn_pretrained.pth"
    checksum: ""
    
# Edge Detection Parameters
edge_detection:
  # HED
  hed:
    crop_size: 500  # Für GPU Memory Management
    scale: 1.0
    mean: [104.00699, 116.66877, 122.67891]
    
  # Structured Forests
  structured_forests:
    scale: 1.0
    
  # Kornia Canny
  kornia:
    low_threshold: 0.1
    high_threshold: 0.2
    kernel_size: 5
    
  # BDCN Fallback (Canny)
  bdcn_fallback:
    blur_kernel: 5
    canny_low: 50
    canny_high: 150
    morph_kernel: 3
    
  # Fixed Edge CNN (Sobel)
  fixed_cnn:
    kernel: [[-1,0,1],[-2,0,2],[-1,0,1]]
    
# Output Settings
output:
  # Bildformate
  save_format: "png"  # png, jpg, tiff, webp
  jpg_quality: 95
  png_compression: 6  # 0-9
  
  # Verarbeitung
  preserve_structure: true  # Unterordner beibehalten
  skip_existing: false  # Bereits verarbeitete Bilder überspringen
  
# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "edge_detection.log"
  console: true
  
# Unterstützte Bildformate
supported_formats:
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".bmp"
  - ".tiff"
  - ".tif"
  - ".webp"
  - ".jp2"  # JPEG 2000
